{{-
/*
*
* K2HR3 Helm Chart
*
* Copyright 2022 Yahoo! Japan Corporation.
*
* K2HR3 is K2hdkc based Resource and Roles and policy Rules, gathers 
* common management information for the cloud.
* K2HR3 can dynamically manage information as "who", "what", "operate".
* These are stored as roles, resources, policies in K2hdkc, and the
* client system can dynamically read and modify these information.
*
* For the full copyright and license information, please view
* the license file that was distributed with this source code.
*
* AUTHOR:   Takeshi Nakatani
* CREATE:   Wed Jan 19 2022
* REVISION:
*
*/ -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-k2hr3-ca-{{ include "k2hr3.clusterName" . }}
  namespace: default
type: Opaque
data:
  {{ $cacertfile := printf "%s.%s_CA.crt" (include "k2hr3.k8sNamespace" .) (include "k2hr3.k2hr3BaseDomain" .) -}}
  {{ $cakeyfile  := printf "%s.%s_CA.key" (include "k2hr3.k8sNamespace" .) (include "k2hr3.k2hr3BaseDomain" .) -}}
  {{ $ca         := fromYaml (include "k2hr3.cacert" .) -}}
  {{ $cacertfile }}: {{ $ca.Cert }}
  {{ $cakeyfile }}: {{ $ca.Key }}

{{-
/*
* Local variables:
* tab-width: 4
* c-basic-offset: 4
* End:
* vim600: noexpandtab sw=4 ts=4 fdm=marker
* vim<600: noexpandtab sw=4 ts=4
*/ -}}
