{{-
/*
*
* K2HR3 Helm Chart
*
* Copyright 2022 Yahoo Japan Corporation.
*
* K2HR3 is K2hdkc based Resource and Roles and policy Rules, gathers 
* common management information for the cloud.
* K2HR3 can dynamically manage information as "who", "what", "operate".
* These are stored as roles, resources, policies in K2hdkc, and the
* client system can dynamically read and modify these information.
*
* For the full copyright and license information, please view
* the license file that was distributed with this source code.
*
* AUTHOR:   Takeshi Nakatani
* CREATE:   Wed Jan 19 2022
* REVISION:
*
*/ -}}
{{- if ne (include "k2hr3.serviceAccountName" .) "default" }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k2hr3.serviceAccountName" . }}
  namespace: {{ include "k2hr3.k8sNamespace" . }}
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-{{ include "k2hr3.r3apiBaseName" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-{{ include "k2hr3.r3apiBaseName" . }}
roleRef:
  kind: ClusterRole
  name: cr-{{ include "k2hr3.r3apiBaseName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "k2hr3.serviceAccountName" . }}
  namespace: {{ include "k2hr3.k8sNamespace" . }}

{{- end }}
{{-
/*
* Local variables:
* tab-width: 4
* c-basic-offset: 4
* End:
* vim600: noexpandtab sw=4 ts=4 fdm=marker
* vim<600: noexpandtab sw=4 ts=4
*/ -}}
